name: Publish

on:
  release:
    types: [published, edited]

env:
  PRIMARY_NODE_VERSION: 12

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      # The source tree will only include: dist/index.js and action.yml
      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - name: Create or update tags
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
